apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gmrj77izi-nodejs
  janus-idp.io/tekton: gmrj77izi-nodejs
  backstage.io/kubernetes-id: gmrj77izi-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gmrj77izi-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
